### ISSUE TITLE
By.css is not implemented. You only have By.cssSelector

### ISSUE THREAD

**Issue by totty90** [jsdevel/webdriver-sync#99]
I'm migrating from webdriver from selenium and it has By.css

**Comment by jsdevel** [comment]
Historically webdriver-sync has only been a wrapper.  By doesn't have CSS http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/By.html.

However, I think we could make an exception here.  Thoughts @NickTullet?

**Comment by totty90** [comment]
Now I understand that you just want to implement the Java API and not JavaScript API. (from your readme)

But would be nice to have the ".css" alias.

**Comment by jsdevel** [comment]
I like the idea of aliases a _lot_.  It would make this lib terser.

**Comment by NickTulett** [comment]
I've written my own $() wrapper to use sizzle-like syntax for selectors - I prefer very terse, but then again noone else has to read my scripts (yet)

**Comment by hackhat** [comment]
Here is the selenium-sync way with all the goodies included out of the box (easy css selector, sync and non blocking, multi window management..)

**Comment by jugglinmike** [comment]
More and more I find myself building an abstraction around the selection mechanism. Given a file named `selectors.json` like this:

```json
{
  "loginBtn": ".login button:first-child"
}
```

...this abstraction does a lookup and uses the `By.cssSelector`, something like `$('loginBtn')`. This reduces repetition and makes it easier for others to modify the DOM without having to touch test code directly. (Maybe this is what @NickTulett was describing, too?).

So since I'm already wrapping the selection mechanism, a shorter alias isn't really important to me.

**Comment by tandrewnichols** [comment]
Ditto. We use a jquery-esque wrapper.

**Comment by NickTulett** [comment]
I've thrown together my ideas for both webdriver-sync and webpagetest here:
http://nicktulett.github.io/TestingWithNode/

(Very much a work in progress)

**Comment by jsdevel** [comment]
Seeing as how `webdriver-sync` is just a wrapper around the Java API, I'm going to close it.  Feel free to publish convenience wrappers around `webdriver-sync`.
